購入履歴ページを追加#14
jyunya-takahashi/lamp_practice pull request #15
Opened 2020-09-27 13:33 UTC by jyunya-takahashi

@primestyleus 
購入履歴ページと購入履歴詳細ページを追加しました。
ご確認とマージをお願いいたします。

2020-09-27 14:26 UTC, primestyleus requested changes
@jyunya-takahashi 
SUMやGROUP BYも正しく使えていて、きれいな形で完成していると思います！
詳細画面へのデータ引き渡しですが、order_id以外は、改めてDBから取り出したほうが良いかと思います。

2020-09-27 14:26 UTC, primestyleus commented on www/view/order_view.php
> +                <input type="hidden" name="total_price" value="<?php print($order['total_price']); ?>">
order_data, order_priceは詳細画面でDBからとるようにしましょう。

2020-09-27 14:26 UTC, primestyleus commented on www/view/order_details_view.php
> +            <td><?php print h($order_detail['order_price']); ?>円</td>
金額にはnumber_formatを使いましょう。

2020-09-28 12:57 UTC, jyunya-takahashi commented
@primestyleus 
以下修正しました。
ご確認とマージをお願いいたします。
・金額にはnumber_formatを使用
・購入詳細画面へのPOSTをorder_idのみに変更し、dbより再取得

2020-09-28 13:07 UTC, primestyleus approved these changes

2020-09-28 13:07 UTC, primestyleus commented on www/model/order.php
> +  return fetch_all_query($db, $sql, $params);
1件取得の場合、fetch_queryを使ったほうが、きれいです。

2020-09-28 13:08 UTC, merged